name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict

  spell:
    name: Spell
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: npm install -g git+https://github.com/streetsidesoftware/cspell-cli

      - name: Run CSpell
        run: cspell-cli lint --no-progress

  build:
    name: Build
    runs-on: macos-15
    strategy:
      matrix:
        config: ['debug', 'release']
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build in ${{ matrix.config }}
        run: swift build -c ${{ matrix.config }}

  test:
    name: Test
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run tests
        run: swift test
